### ISSUE TITLE
Filter "|number" documentation error

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#58]
**Describe the bug**
When I hover "|number" filter the pop-up says `|number:(decimals: int = 0, thousandsSep: string = ',', decPoint: string = '.')`, but it should be `number (int decimals = 0, string decPoint = '.', string thousandsSep = ',')`. The `decPoint` and `thousandsSep` are switched in documentation.

**Environment (please complete the following information):**
 - PhpStorm version [e.g. 2022.2.1]
 - Plugin version [e.g. 1.0.6]

**Screenshots**
![image](https://user-images.githubusercontent.com/15814845/188495932-91bb0507-912c-4b42-93c8-47d9c7d7c3a1.png)

**Comment by mesour** [comment]
@martinbohmcz fixed in 1.0.8, please test it.

**Comment by martinbohmcz** [comment]
Unfortunately it is still the same at me:
![image](https://user-images.githubusercontent.com/15814845/194280752-f41290f7-bccf-4071-91c7-322451cbc9d3.png)
